repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        additional_dependencies:
          - "prettier@2.8.8"
          - "prettier-plugin-java@2.3.1"
        types:
          - "java"
        args:
          - --plugin=prettier-plugin-java
